#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep -w 'DP1 connected') ]]; then
    xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --mode 1440x900 --pos 1920x47 --rotate normal 
    bspc monitor eDP1 -d I II III IV V
    bspc monitor DP1 -d  VI VII VII IX X
else
    bspc monitor -d I II III IV V VI VII VII IX X
fi


bspc config border_width        2
bspc config window_gap          25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

IRONIC_WM_NAME="LG3D"
NET_WIN=$(xprop -root _NET_SUPPORTING_WM_CHECK | awk -F "# " '{print $2}')

if [[ "$NET_WIN" == 0x* ]]; then
    # xprop cannot reliably set UTF8_STRING, so we replace as string.
    # fortunately, jdk is OK with this, but wm-spec says use UTF8_STRING.
    xprop -id "$NET_WIN" -remove _NET_WM_NAME
    xprop -id "$NET_WIN" -f _NET_WM_NAME 8s -set _NET_WM_NAME "$IRONIC_WM_NAME"
else
    # even if we're not net compatible, do java workaround
    xprop -root -remove _NET_WM_NAME
    xprop -root -f _NET_WM_NAME 8s -set _NET_WM_NAME "$IRONIC_WM_NAME"
fi
xsetroot -cursor_name left_ptr &

touchpad_id=$(xinput -list | sed '/Touchpad/s/.*id=\([0-9]*\).*/\1/;t;d')
echo $touchpad_id
xinput set-prop $touchpad_id 'libinput Tapping Enabled' 1
xinput set-prop $touchpad_id 'libinput Natural Scrolling Enabled' 1


feh --bg-scale /home/abdiel/Pictures/wallpapers/archgruv2.png
picom &
$HOME/.config/polybar/launch.sh &
#redshift -l 19.432608:-99.133209 &
dunst &
